### ISSUE TITLE
Arreglar errores en la gestión de combos

### ISSUE THREAD

**Issue by samuelbustosp** [NAMP-SA/frontend-ecommerce-namp#3]
La creación de combos actualmente lanza un error **500** en el servidor.
**Próximos Pasos** 
Se recomienda probar la funcionalidad de creación de combos y verificar que todos los casos de error se manejen adecuadamente.

**Cambios realizados**
- Contenedor de Combos: Se implementó el ComboContainer, que ahora maneja la lógica de estado y la interacción con la API para la creación y gestión de combos.
- Lista de Combos: Se desarrolló el ComboList, que muestra todos los combos disponibles, permitiendo su visualización y selección para editar o eliminar.
- Modal de Combos: Se creó el ComboModal, que permite a los usuarios agregar y editar combos, incluyendo la carga de imágenes y la selección de productos asociados.

**Referencias**
Este trabajo está relacionado con la issue #1 sobre registar combos.

**Comment by gonzabaldassi** [comment]
No había errores, se estaba pasando productCombo dentro del combo y esto no se puede, primero se tiene que crear el combo.
